# Generated by Django 3.2.8 on 2021-12-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcards_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
